use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use crate::constants::*;
use crate::error::Error;

/// toq configuration, loaded from `~/.toq/config.toml`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    pub agent_name: String,
    pub host: String,
    pub port: u16,
    pub connection_mode: String,
    pub verbosity: String,
    pub log_level: String,
    pub accept_files: bool,
    pub max_file_size: usize,
    pub max_message_size: usize,
    pub max_connections: usize,
    pub max_threads_per_connection: usize,
    pub max_message_queue: usize,
    pub max_pending_approvals: usize,
    pub handshake_timeout: u64,
    pub negotiation_timeout: u64,
    pub ack_timeout: u64,
    pub heartbeat_interval: u64,
    pub heartbeat_timeout: u64,
    pub session_resume_timeout: u64,
    pub graceful_shutdown_timeout: u64,
    pub log_retention_days: u32,
    pub log_max_size_mb: u32,
    pub thread_cleanup_days: u32,
    pub mdns_enabled: bool,
    pub api_port: u16,
    pub adapter: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_history_limit: Option<usize>,
    #[serde(rename = "adapter.http", skip_serializing_if = "Option::is_none")]
    pub adapter_http: Option<HttpAdapterConfig>,
    #[serde(rename = "adapter.grpc", skip_serializing_if = "Option::is_none")]
    pub adapter_grpc: Option<GrpcAdapterConfig>,
    #[serde(rename = "adapter.unix", skip_serializing_if = "Option::is_none")]
    pub adapter_unix: Option<UnixAdapterConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HttpAdapterConfig {
    pub callback_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GrpcAdapterConfig {
    pub address: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnixAdapterConfig {
    pub socket_path: String,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            agent_name: "agent".into(),
            host: "localhost".into(),
            port: DEFAULT_PORT,
            connection_mode: "approval".into(),
            verbosity: "non-technical".into(),
            log_level: "warn".into(),
            accept_files: false,
            max_file_size: DEFAULT_MAX_FILE_SIZE,
            max_message_size: DEFAULT_MAX_MESSAGE_SIZE,
            max_connections: DEFAULT_MAX_CONNECTIONS,
            max_threads_per_connection: DEFAULT_MAX_THREADS_PER_CONNECTION,
            max_message_queue: DEFAULT_MESSAGE_QUEUE_DEPTH,
            max_pending_approvals: MAX_PENDING_APPROVALS,
            handshake_timeout: HANDSHAKE_TIMEOUT.as_secs(),
            negotiation_timeout: NEGOTIATION_TIMEOUT.as_secs(),
            ack_timeout: ACK_TIMEOUT.as_secs(),
            heartbeat_interval: HEARTBEAT_INTERVAL.as_secs(),
            heartbeat_timeout: HEARTBEAT_TIMEOUT.as_secs(),
            session_resume_timeout: SESSION_RESUME_TIMEOUT.as_secs(),
            graceful_shutdown_timeout: GRACEFUL_SHUTDOWN_TIMEOUT.as_secs(),
            log_retention_days: LOG_RETENTION_DAYS,
            log_max_size_mb: LOG_MAX_SIZE_MB,
            thread_cleanup_days: THREAD_CLEANUP_DAYS,
            mdns_enabled: false,
            api_port: DEFAULT_API_PORT,
            adapter: "http".into(),
            message_history_limit: None,
            adapter_http: None,
            adapter_grpc: None,
            adapter_unix: None,
        }
    }
}

impl Config {
    /// Create a config with custom agent name and connection mode, defaults for everything else.
    pub fn with_agent(mut self, name: String, mode: String) -> Self {
        self.agent_name = name;
        self.connection_mode = mode;
        self
    }

    /// Set the host address.
    pub fn with_host(mut self, host: String) -> Self {
        self.host = host;
        self
    }

    /// Set the adapter type.
    pub fn with_adapter(mut self, adapter: String) -> Self {
        self.adapter = adapter;
        self
    }

    /// Default config file path: `~/.toq/config.toml`
    pub fn default_path() -> PathBuf {
        dirs_path().join(CONFIG_FILE)
    }

    /// Load config from a TOML file. Returns defaults if file doesn't exist.
    pub fn load(path: &Path) -> Result<Self, Error> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let contents = std::fs::read_to_string(path).map_err(|e| Error::Io(e.to_string()))?;
        toml::from_str(&contents).map_err(|e| Error::Io(e.to_string()))
    }

    /// Save config to a TOML file with annotated comments.
    pub fn save(&self, path: &Path) -> Result<(), Error> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| Error::Io(e.to_string()))?;
        }
        let toml_str = toml::to_string_pretty(self).map_err(|e| Error::Io(e.to_string()))?;
        let annotated = format!(
            "# toq protocol configuration\n\
             # Generated by `toq setup`. Edit values as needed.\n\
             # Documentation: https://github.com/toqprotocol/toq-spec\n\n\
             {toml_str}"
        );
        std::fs::write(path, annotated).map_err(|e| Error::Io(e.to_string()))
    }
}

/// The `~/.toq/` directory path.
pub fn dirs_path() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
    PathBuf::from(home).join(TOQ_DIR_NAME)
}

/// Permission rule as stored in `permissions.toml`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PermissionEntry {
    #[serde(rename = "type")]
    pub rule_type: String,
    pub value: String,
}

/// Permissions file at `~/.toq/permissions.toml`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PermissionsFile {
    #[serde(default)]
    pub approved: Vec<PermissionEntry>,
    #[serde(default)]
    pub blocked: Vec<PermissionEntry>,
    #[serde(default)]
    pub pending: Vec<PendingEntry>,
}

/// A pending approval request.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PendingEntry {
    pub key: String,
    pub address: String,
    pub requested_at: String,
}

impl PermissionsFile {
    pub fn path() -> PathBuf {
        dirs_path().join("permissions.toml")
    }

    pub fn load(path: &Path) -> Result<Self, Error> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let contents = std::fs::read_to_string(path).map_err(|e| Error::Io(e.to_string()))?;
        toml::from_str(&contents).map_err(|e| Error::Io(e.to_string()))
    }

    pub fn save(&self, path: &Path) -> Result<(), Error> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| Error::Io(e.to_string()))?;
        }
        let toml_str = toml::to_string_pretty(self).map_err(|e| Error::Io(e.to_string()))?;
        let annotated = format!(
            "# toq permission rules\n\
             # Edit while the daemon is stopped, or use CLI commands while running.\n\
             # Types: \"key\" (public key) or \"address\" (toq address or wildcard)\n\
             # Wildcards: toq://*, toq://host/*, toq://*/name\n\n\
             {toml_str}"
        );
        std::fs::write(path, annotated).map_err(|e| Error::Io(e.to_string()))
    }
}
